# Put action within a raw block so that the curly bracket expressions aren't picked up by the cookiecutter
#
name: build-push
on:
  push:
    branches: "**"

jobs:
  frontend:
    if: ${{ false && always() }}
    permissions: write-all
    uses: ./.github/workflows/build-fe.yml
    secrets: inherit
  backend:
    if: ${{ false && always() }}
    permissions: write-all
    uses: ./.github/workflows/build-one.yml
    with:
      service: backend
    secrets: inherit
  worker:
    if: ${{ false && always() }}
    permissions: write-all
    uses: ./.github/workflows/build-one.yml
    with:
      service: worker
    secrets: inherit